### PR TITLE
make title and game have the same priority in search

### PR DESCRIPTION
**Pull request by red031000**

### CODE REVIEW

**Comment by Felk** [comment]
what's the rationale?

**Comment by red031000** [comment]
see TwitchPlaysPokemon/public#72 (in short, search requests that only specify the game will get that game after requests that are close to the game's title in the name of the song)

**Comment by Felk** [comment]
looks good, but regarding the search weighting: please play around with it a bit, and see if the results feel good

**Comment by red031000** [comment]
I've adjusted it to 0.9, since that gives better results than 1.0 or 0.8

**Comment by Felk** [comment]
LGTM

should I merge? And do you need a tag pushed for the version?

**Comment by red031000** [comment]
yes please, I do need the version published

**Pull request merged**
